# Face detection In Images

In [1]:
import numpy as np
import cv2

In [2]:
img=cv2.imread('./images/faces.jpg')
cv2.imshow('face',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
face_cascade=cv2.CascadeClassifier('./model/haarcascade_frontalface_default.xml')

In [4]:
def face_detection(img):
    image=img.copy()
    # step 1: convert image to grayscale
    gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    # step 2: apply gray scale to cascade classifier
    box,detections=face_cascade.detectMultiScale2(gray,minNeighbors=6)
    print(box)
    for x,y,w,h in box:
        cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,0),1)
    
    return image

# The face_cascade.detectMultiScale2() function is used to detect faces in the grayscale image. 
# It takes the grayscale image as input and uses a cascade classifier previously trained on face detection.
# The minNeighbors parameter specifies the number of neighbors a candidate rectangle should have to retain it. 
# Increasing this value results in fewer detections but with higher quality. 
# The function returns two values: box and detections. box contains the coordinates and dimensions of the detected faces, 
# while detections represents the detection confidence scores.

In [5]:
img_detect=face_detection(img)
cv2.imshow('face_detection',img_detect)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[379  49  65  65]
 [367 316 106 106]
 [438 218  69  69]
 [167 224  74  74]
 [175  55  67  67]]


In [6]:
image=img.copy()
# step 1: convert image to grayscale
gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
# step 2: apply gray scale to cascade classifier
box,detections=face_cascade.detectMultiScale2(gray,minNeighbors=14)
for x,y,w,h in box:
    cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,0),1)
    
cv2.imshow('face_detection1',image)
cv2.waitKey(0)
cv2.destroyAllWindows()
   

In [7]:
detections

array([28, 47, 24, 83, 82])

In [8]:
box

array([[379,  49,  65,  65],
       [367, 316, 106, 106],
       [175,  55,  67,  67],
       [438, 218,  69,  69],
       [167, 224,  74,  74]])

# Realtime Face Detection(Videos)

In [9]:
cap= cv2.VideoCapture(0)
face_cascade=cv2.CascadeClassifier('./model/haarcascade_frontalface_default.xml')

In [ ]:
while True:
    ret,frame=cap.read()
    if ret==False:
        break
    img_detect=face_detection(frame)
    cv2.imshow('realtime face detection',img_detect)
    if cv2.waitKey(1)==ord('a'):
        break
cap.release()
cv2.destroyAllWindows()


[[140 324  60  60]
 [284 217 189 189]]
[[283 218 188 188]]
[[143 325  55  55]
 [282 217 191 191]]
[[141 324  60  60]
 [282 217 192 192]]
[[138 323  63  63]
 [280 216 192 192]]
[[279 217 193 193]]
[[142 325  58  58]
 [281 219 190 190]]
[[140 326  58  58]
 [280 218 192 192]]
[[142 327  56  56]
 [281 218 191 191]]
[[142 327  58  58]
 [282 219 189 189]]
[[281 218 191 191]]
[[139 326  60  60]
 [283 220 188 188]]
[[282 218 190 190]]
[[282 218 189 189]]
[[141 327  57  57]
 [283 219 188 188]]
[[140 326  58  58]
 [281 218 192 192]]
[[140 325  58  58]
 [280 218 192 192]]
[[141 327  57  57]
 [280 217 193 193]]
[[141 325  60  60]
 [283 218 191 191]]
[[283 218 189 189]
 [141 325  59  59]]
[[140 325  60  60]
 [281 218 191 191]]
[[139 324  61  61]
 [282 217 191 191]]
[[282 217 191 191]
 [141 326  57  57]]
[[142 327  56  56]
 [281 217 192 192]]
[[142 326  58  58]
 [284 219 190 190]]
[[142 325  58  58]
 [291 218 186 186]]
[[140 325  59  59]
 [296 213 193 193]]
[[297 211 195 195]]
[[305 209 194 194]]
[[